# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiqa" do
  version "0.41.2"

  on_macos do
    on_intel do
      sha256 "e0ac527962760454ab450ba11a6155bce002fed2190ca84b0721390a7ab46df2"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e82890349bea8e94ebef01964f732ed5e58331cabc272aa8ecaa25e32df0cb47"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0fd0682b6b93d6bf86917e8f5c4551229846d853bf7846390ab6750959fdc211"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "47876a3b5b00873efef47201bc91cd0a3d575afc0dd6794213c8359c82efa50b"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aiqa"
  desc "Command-line client for the Aiqaramba QA platform API"
  homepage "https://aiqaramba.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiqa"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aiqa"]
    end
  end

  # No zap stanza required

end
