# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiqa" do
  version "0.41.0"

  on_macos do
    on_intel do
      sha256 "ec217f6fa82310e4827c414ece8e28b16b6fcc309e56e3dbb7ee015cdb1fb35d"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6c748981a7b13af8c7866fa25683d9ce757fc5d4f2f91ef18545d093452a8a7"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bafa0ead7ad04986831a5096691f9a875e58f2183164e0b9051323c97c3be43f"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "036fc4062ea07d360cffee8f5e19fd3608fc6f514a584d49d0a4424d830d9db5"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aiqa"
  desc "Command-line client for the Aiqaramba QA platform API"
  homepage "https://aiqaramba.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiqa"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aiqa"]
    end
  end

  # No zap stanza required

end
