# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiqa" do
  version "0.40.0"

  on_macos do
    on_intel do
      sha256 "0d2b111d099d4483a6b93a9d91210f3706fb035aa8c27b3644ded09d0aebd16f"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1700c2900f33e05db2ee6a0d5b551cf43ff915ef39572987746cb7fcaa475214"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7064cf2bd05e92a81351897b0aa3379f152e08a8a809a0de75d869c8f8fb696c"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "64a860c55b1a39ae87d2703cc3cd76c9b01e2695aa0480bb9705d27651a5d02a"
      url "https://github.com/alex-ai-eu/homebrew-tap/releases/download/v#{version}/aiqa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aiqa"
  desc "Command-line client for the Aiqaramba QA platform API"
  homepage "https://aiqaramba.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiqa"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aiqa"]
    end
  end

  # No zap stanza required

end
